export enum PartSet {
    RIGHT_ITEM = 'ri',
    RIGHT_HAND = 'rh',
    RHS = 'rhs', //?
    RIGHT_SLEEVE = 'rs', // right shirt arm
    rc = 'rc', // right arm (jacket ?)
    BODY = 'bd',
    BODIES = 'bds',
    ss = 'ss',
    SHOES = 'sh',
    LEG = 'lg',
    CHEST_SHIRT = 'ch', // chest shirt
    CHEST_PRINT = 'cp', // chest print
    CHEST_JACKET = 'cc', // chest jacket
    CHEST_ACC = 'ca', // chest accessory
    HEAD = 'hd',
    FACE = 'fc',
    EYES = 'ey',
    HAIR = 'hr',
    HAIR_BIG = 'hrb',
    LEFT_ITEM = 'li',
    LEFT_HAND = 'lh',
    LHS = 'lhs',
    LEFT_SHIRT = 'ls', // left shirt arm
    LEFT_COAT_SLEEVE = 'lc', // left arm (jacket ?)
    WAIST_ACC = 'wa', // waist accesory
    EYE_ACC = 'ea', // eye accesory
    FACE_ACC = 'fa', // face accesory
    HAT = 'ha', // hat
    HEAD_ACC = 'he', // head accesory
}
