export enum UIComponent {
    BottomBarUI = 'bottomBar',
    TopBarUI = 'topBar',
    GameLoaderUI = 'gameLoader',
    RoomUI = 'roomUI',
    NavigatorUI = 'navigator',
    FriendsMenuUI = 'friends',
    PreviewBoxUI = 'preview',
    StaticContainerUI = 'static',
    ListUI = 'list',
    CreateRoomUI = 'createRoom',
    CatalogueUI = 'catalogue',
    RoomInfoUI = 'roomInfo',
    RoomEditInfoUI = 'roomEdit',
    DefaultPanelUI = 'defaultPanel',
    UserPanelUI = 'userPanel',
    AvatarContainerUI = 'avatarContainer',
    InventoryUI = 'inventory',
    PrivateChatUI = 'private',
}
